version: "3.9"

x-env: &app
  build: "./.docker/php"
  working_dir: "/app"
  volumes:
    - ".:/app:cached"
    - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"

services:
  nginx:
    build: "./.docker/nginx"
    ports:
      - "80:80"
    volumes:
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./public:/app/public"
    depends_on:
      - app

  app:
    <<: *app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    volumes:
      - "mysql_store:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

  redis:
    image: redis:6.0.8-alpine
    ports:
      - "6379:6379"
    volumes:
      - "redis_store:/data"

  queue_worker:
    build: "./.docker/php"
    working_dir: "/app"
    command: "php artisan queue:work --tries=3"
    volumes:
      - ".:/app"
      - "./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini"

#  asset_watcher:
#    <<: *node
#    command: "yarn run watch-poll"
#    ports:
#      - "3000:3000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - "./storage/minio:/storage"
    command: server /storage
    environment:
      MINIO_ACCESS_KEY: ${AWS_ACCESS_KEY_ID:-root}
      MINIO_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY:-password}
      MINIO_REGION: ${AWS_DEFAULT_REGION:-ap-northeast-1}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - "9090:80"

volumes:
  mysql_store:
  redis_store:
